export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SPECIFIC_ERRORS = 'CLEAR_SPECIFIC_ERRORS';

export const REPOS_LOADING = 'REPOS_LOADING';
export const GET_REPOS = 'GET_REPOS';

export const SET_NEW_PROJECT_REPO_URL = 'SET_NEW_PROJECT_REPO_URL';
export const CLEAR_NEW_PROJECT_REPO_URL = 'CLEAR_NEW_PROJECT_REPO_URL';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const GET_PROJECT = 'GET_PROJECT';
export const DELETE_TAG_AT_INDEX = 'DELETE_TAG_AT_INDEX';
export const ADD_TAG = 'ADD_TAG';
export const DELETE_IMAGE_AT_INDEX = 'DELETE_IMAGE_AT_INDEX';
export const ADD_IMAGE = 'ADD_IMAGE';
export const CHANGE_IMAGE_TITLE = 'CHANGE_IMAGE_TITLE';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';
export const PROJECT_IMAGES_URLS = 'PROJECT_IMAGES_URLS';
export const SEARCHING_PROJECTS = 'SEARCHING_PROJECTS';
export const GET_SEARCHED_PROJECT = 'GET_SEARCHED_PROJECT';
