export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const REPOS_LOADING = 'REPOS_LOADING';
export const GET_REPOS = 'GET_REPOS';

export const SET_NEW_PROJECT_REPO_URL = 'SET_NEW_PROJECT_REPO_URL';
export const CLEAR_NEW_PROJECT_REPO_URL = 'CLEAR_NEW_PROJECT_REPO_URL';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const GET_PROJECT = 'GET_PROJECT';
export const DELETE_TAG_AT_INDEX = 'DELETE_TAG_AT_INDEX';
export const ADD_TAG = 'ADD_TAG';
export const DELETE_IMAGE_AT_INDEX = 'DELETE_IMAGE_AT_INDEX';
export const ADD_IMAGE = 'ADD_IMAGE';
